Cargo.lock, Cargo.toml, src/protocol/hand_shake.rs, src/sql_handler.rs, src/storage.rs
=> send not supported operation message instead of panicing

src/bin.rs, src/protocol/channel.rs, src/protocol/connection.rs, src/protocol/hand_shake.rs, src/protocol/mod.rs, src/sql_handler.rs, test_helpers/src/async_io.rs, test_helpers/src/frontend.rs, tests/sql/mod.rs
=> Support rust postgres driver

src/bin.rs, src/lib.rs, src/node.rs, tests/sql/mod.rs
=> setup running skeleton with automated tests

.github/workflows/rust.yml, compatibility/02_table_with_multiple_columns.sql, src/node.rs, src/protocol/connection.rs, src/sql_handler.rs, src/storage.rs, tests/integration_sql/mod.rs, tests/mod.rs, tests/sql/mod.rs
=> Support multiple columns

src/sql_engine/src/lib.rs, src/storage/src/frontend.rs
=> improve error handling in sql engine

Cargo.lock, compatibility/03_different_types.sql, src/node/src/node.rs, src/sql_engine/src/lib.rs, src/sql_types/src/lib.rs, src/sql_types/src/types.rs, src/storage/Cargo.toml, src/storage/src/frontend/mod.rs, src/storage/src/frontend/tests/queries/insert.rs, src/storage/src/frontend/tests/queries/select.rs
=> support character strings

README.md
=> added project description to readme file

src/node/src/node.rs, src/node/src/query_listener.rs, src/protocol/src/lib.rs, src/protocol/src/listener.rs, src/protocol/src/messages.rs
Initial documentation for `protocol` crate. Work is done under #64
=> added first iteration docs for PostgreSQL wire protocol

Cargo.lock, src/sql_engine/Cargo.toml, src/sql_engine/src/lib.rs, src/storage/src/frontend/mod.rs, src/storage/src/frontend/tests/queries/delete.rs, src/storage/src/frontend/tests/queries/insert.rs, src/storage/src/frontend/tests/queries/select.rs, src/storage/src/frontend/tests/queries/update.rs, src/storage/src/frontend/tests/schema.rs, src/storage/src/frontend/tests/table.rs
=> cover operations on non existent schemas and tables

README.md
Instead, explicitly show that its a placeholder for a file name.
=> There are no such file.

.github/workflows/rust.yml, Cargo.lock, Dockerfile, action.yml, ci/clippy.sh, ci/local-clippy.sh, ci/local-rustfmt.sh, ci/rustfmt.sh, src/node/Cargo.toml, src/node/src/bin.rs, src/node/src/node.rs, src/protocol/Cargo.toml, src/protocol/src/lib.rs, src/protocol/src/listener.rs, src/sql_engine/Cargo.toml, src/sql_types/Cargo.toml, src/sql_types/src/lib.rs, src/storage/src/backend.rs
=> configure ci to run functional tests

Cargo.lock, src/sql_engine/Cargo.toml, src/sql_engine/src/lib.rs, src/storage/src/backend.rs, src/storage/src/frontend/mod.rs, src/storage/src/frontend/tests/queries/delete.rs, src/storage/src/frontend/tests/queries/insert.rs, src/storage/src/frontend/tests/queries/select.rs, src/storage/src/frontend/tests/queries/update.rs, src/storage/src/frontend/tests/schema.rs, src/storage/src/frontend/tests/table.rs, src/test_helpers/Cargo.toml, src/test_helpers/src/in_memory_backend_storage.rs
* introduce simplification into `FrontendStorage` by adding `create_namespace_with_objects` to `BackendStorage`.
* migrate `BackendStorage` tests to `rstest`
=> updates in storage code

tests/functional/basic_queries_tests.py
1) try-except blocks removed
2) new ficture created to create/drop schema for each function, when create_cursor runs one time on start
=> new logic for functional tests

src/protocol/src/listener.rs, tests/functional/queries_with_sql_types.py
try-except blocks were removed, second fixture for updating test schema/table was introduced
=> SQL types tests improvements

src/sql_engine/src/ddl/create_table.rs, src/sql_engine/src/dml/insert.rs, src/sql_types/src/lib.rs, src/storage/src/frontend/mod.rs, tests/functional/queries_with_sql_types.py
=> Support boolean types

README.md
=> update coveralls badge

src/protocol/src/lib.rs, src/protocol/src/messages.rs, src/protocol/src/results.rs, src/sql_engine/src/ddl/create_table.rs, src/sql_engine/src/dml/delete.rs, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/mod.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/tests/insert.rs, src/sql_engine/src/tests/update.rs, src/sql_types/src/lib.rs
Part of #127 
* adds math operations and string concatenation inside update statements
* removes memory allocation for errors code and severity
=> math operation and concatenation in update queries

src/storage/src/backend.rs, src/storage/src/frontend/mod.rs, src/storage/src/lib.rs, src/test_helpers/src/in_memory_backend_storage.rs
No Issue
Added a TableDescription struct for representing a table at runtime. When this struct is built it will generate appropriate error is the schema or requested table does not exist.
No changes.
=> Table Description API

Dockerfile, docs/README.md
fixing failing CI on master due to recent changes to support TLS for PG protocol
=> install openssl inside container

src/sql_types/src/lib.rs, src/storage/src/frontend/mod.rs
Closes #142
Refactored validation/serialization logic in FrontendStorage to reduce code duplication.
All functional tests passed:
```
=============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.7.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1 -- /Library/Developer/CommandLineTools/usr/bin/python3
cachedir: .pytest_cache
rootdir: /Users/vkulichenko/database
collected 19 items                                                                                                                                                                
tests/functional/basic_queries_tests.py::test_create_duplicate_schema PASSED …
```
=> Minor refactoring of validation/serialization logic in FrontendStorage (#142)

src/protocol/src/results.rs
Closes #176
refactor the QueryErrorKind enum
============================================================================================================ test session starts ============================================================================================================platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/xxx/source/database
collected 19 items
tests/functional/basic_queries_tests.py::test_create_duplicate_schema PASSED                                                                                                                                                          [  5%]
tests/functional/basic_queries_tests.py::test_create_drop_schema PASSED …
=> refactor QueryErrorKind using c-like enum variant (#176)

src/protocol/src/listener.rs, src/protocol/src/tests/hand_shake.rs
use state machine to establish PostgreSQL connection with client
No changes to output
=> use state machine to establish PostgreSQL connection with client

.github/workflows/release.yml
Closes #125 
adds GH action to publish docker image on release creation
=> add on release workflow

.github/workflows/release.yml, CHANGELOG.md
=> add change log

src/sql_types/src/lib.rs, src/storage/src/frontend/mod.rs
Reverts alex-dukhno/database#206 as it does not handle a `DROP TABLE SCHEMA_NAME.USER_TABLE` case
Reopen #114
=> Revert "SQL API for system tables (#114)"

.github/workflows/merge.yaml, .github/workflows/pull-requests.yml, Cargo.lock, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/sql_types/src/lib.rs, src/storage/Cargo.toml, src/storage/src/backend.rs, src/storage/src/frontend/mod.rs
`impl Into<PostgreSqlType> for &SqlType`
no changes
=> introduce Into<PostgreSqlType> for &SqlType

Dockerfile, src/node/src/node.rs
Closes #256
configure persistence for docker container, it allows run functional tests against persistent database storage
=> persistence path for docker container to store data

Cargo.lock, src/representation/src/lib.rs, src/sql_engine/src/catalog_manager/data_definition.rs, src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/catalog_manager/tests/queries/delete.rs, src/sql_engine/src/catalog_manager/tests/queries/select.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/storage/Cargo.toml, src/storage/src/in_memory.rs, src/storage/src/lib.rs, src/storage/src/persistent.rs, src/storage/src/tests/in_memory.rs, src/storage/src/tests/mod.rs, src/storage/src/tests/persistent.rs, src/storage/tests/failpoints/drop_db.rs, src/storage/tests/failpoints/drop_tree.rs, src/storage/tests/failpoints/flush_tree.rs, src/storage/tests/failpoints/insert_into_tree.rs, src/storage/tests/failpoints/iterate_over_tree.rs, src/storage/tests/failpoints/open_db.rs, src/storage/tests/failpoints/open_tree.rs, src/storage/tests/failpoints/remove_from_tree.rs
No issue to close. Related to #255
added tests for storage module and also tests to check if `sled` starts return errors
=> improve testing over storage module

src/storage/src/persistent.rs, src/storage/tests/failpoints/flush_tree.rs
=> remove code duplication from persistent database

src/sql_engine/src/catalog_manager/data_definition.rs, src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/catalog_manager/tests/mod.rs, src/sql_engine/src/catalog_manager/tests/persistence.rs, src/sql_engine/src/catalog_manager/tests/table.rs, src/sql_engine/src/lib.rs
Closes #255 
adding tests for `CatalogManager::persistent`
No changes in client output
=> added persistent catalog manager tests

src/sql_engine/src/catalog_manager/data_definition.rs, src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/catalog_manager/tests/persistence.rs, src/sql_engine/src/catalog_manager/tests/queries/delete.rs, src/sql_engine/src/catalog_manager/tests/queries/select.rs, src/sql_engine/src/catalog_manager/tests/schema.rs, src/sql_engine/src/catalog_manager/tests/table.rs, src/sql_engine/src/dml/delete.rs, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/sql_engine/src/query/process.rs, src/storage/src/in_memory.rs, src/storage/src/lib.rs, src/storage/src/persistent.rs, src/storage/src/tests/in_memory.rs, src/storage/src/tests/mod.rs, src/storage/src/tests/persistent.rs, src/storage/tests/failpoints/common.rs, src/storage/tests/failpoints/drop_db.rs, src/storage/tests/failpoints/drop_tree.rs, src/storage/tests/failpoints/flush_tree.rs, src/storage/tests/failpoints/insert_into_tree.rs, src/storage/tests/failpoints/iterate_over_tree.rs, src/storage/tests/failpoints/open_db.rs, src/storage/tests/failpoints/open_tree.rs, src/storage/tests/failpoints/remove_from_tree.rs
refactoring to use `CatalogManager` in `*Command`s structures
=> refactor *Commands to use CatalogManager iteration 1

src/sql_engine/src/catalog_manager/tests/persistence.rs, src/sql_engine/src/ddl/drop_schema.rs, src/sql_engine/src/dml/delete.rs, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/mod.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/query/process.rs
refactoring `*Command`s to use `CatalogManager` second iteration
no changes to output
=> use match over table_exists function

src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/catalog_manager/tests/mod.rs, src/sql_engine/src/catalog_manager/tests/persistence.rs, src/sql_engine/src/catalog_manager/tests/queries/delete.rs, src/sql_engine/src/catalog_manager/tests/queries/select.rs, src/sql_engine/src/catalog_manager/tests/schema.rs, src/sql_engine/src/catalog_manager/tests/table.rs, src/sql_engine/src/ddl/create_table.rs, src/sql_engine/src/query/process.rs, src/sql_engine/src/tests/bind.rs, src/sql_engine/src/tests/bind_prepared_statement_to_portal.rs, src/sql_engine/src/tests/delete.rs, src/sql_engine/src/tests/describe_prepared_statement.rs, src/sql_engine/src/tests/execute_portal.rs, src/sql_engine/src/tests/insert.rs, src/sql_engine/src/tests/mod.rs, src/sql_engine/src/tests/parse_prepared_statement.rs, src/sql_engine/src/tests/schema.rs, src/sql_engine/src/tests/select.rs, src/sql_engine/src/tests/table.rs, src/sql_engine/src/tests/type_constraints.rs, src/sql_engine/src/tests/update.rs
use `u64` schema id to create new table
=> Create table with schema

src/sql_engine/src/catalog_manager/data_definition.rs, src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/catalog_manager/tests/persistence.rs, src/sql_engine/src/catalog_manager/tests/schema.rs, src/sql_engine/src/catalog_manager/tests/table.rs, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs
lookup table columns by schema and table id
=> list table columns by schema and table id

src/sql_engine/src/catalog_manager/mod.rs, src/sql_engine/src/dml/insert.rs, src/storage/src/lib.rs, src/storage/src/persistent.rs
=> introduce record id generator per table

CHANGELOG.md, src/sql_engine/src/dml/update.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/query/bind.rs, src/sql_engine/src/query/plan.rs, src/sql_engine/src/query/process.rs
Closes #189 
minimalistic migration of update query to query planner
=> minimal update query migration to query planner

src/sql_engine/src/dml/delete.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/query/plan.rs, src/sql_engine/src/query/process.rs
Closes #192
migrate delete queries to use query planner
=> minimal delete query migration to query planner

src/sql_engine/src/dml/select.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/query/plan.rs, src/sql_engine/src/query/process.rs, src/sql_engine/src/tests/parse_prepared_statement.rs
Closes #190 
minimal select migration to query planner
=> minimal select migration to query planner

src/data_manager/src/data_definition.rs, src/data_manager/src/lib.rs, src/data_manager/src/tests/manager/persistence.rs, src/data_manager/src/tests/manager/queries.rs, src/data_manager/src/tests/manager/schema.rs, src/data_manager/src/tests/manager/table.rs, src/kernel/src/lib.rs, src/query_planner/src/lib.rs, src/query_planner/src/plan.rs, src/query_planner/src/planner/delete.rs, src/query_planner/src/planner/drop_tables.rs, src/query_planner/src/planner/insert.rs, src/query_planner/src/planner/select.rs, src/query_planner/src/planner/update.rs, src/query_planner/src/tests/delete.rs, src/query_planner/src/tests/drop_table.rs, src/query_planner/src/tests/insert.rs, src/query_planner/src/tests/select.rs, src/query_planner/src/tests/update.rs, src/sql_engine/src/ddl/drop_schema.rs, src/sql_engine/src/ddl/drop_table.rs, src/sql_engine/src/dml/delete.rs, src/sql_engine/src/dml/insert.rs, src/sql_engine/src/dml/select.rs, src/sql_engine/src/dml/update.rs, src/sql_engine/src/lib.rs, src/sql_engine/src/tests/parse_prepared_statement.rs
some cross module API was changed to use std traits
=> generalise cross module apis

src/ast/src/lib.rs
removed `TryFrom<ScalarValue> for Datum` implementation as functionality is moved into `TypeConstraint`
no changes for client output
=> delete unused code in Datum

.github/workflows/compatibility-tests.yml, CONTRIBUTING.md, README.md, build.gradle, local/compatibility.sh, tests/compatibility/src/test/groovy/io/database/ContainersSpecification.groovy
Closes no issues
update to `README` doc
fix compatibility pipeline
no
no changes
=> add docs and compatibility tests

README.md
introduce v1 of todo list in database
no
no changes
=> initial todo list

CHANGELOG.md, Cargo.lock, deny.toml, src/data_manager/Cargo.toml, src/data_manager/src/data_definition.rs, src/data_manager/src/in_memory.rs, src/data_manager/src/lib.rs, src/data_manager/src/persistent.rs, src/data_manager/src/tests/manager/table.rs, src/node/src/query_engine/mod.rs, src/plan/src/lib.rs, src/query_executor/src/dml/select.rs, src/query_executor/src/dml/update.rs, src/query_planner/src/create_schema.rs, src/query_planner/src/create_table.rs, src/query_planner/src/delete.rs, src/query_planner/src/drop_schema.rs, src/query_planner/src/drop_tables.rs, src/query_planner/src/insert.rs, src/query_planner/src/select.rs, src/query_planner/src/update.rs, src/sql_model/Cargo.toml, src/sql_model/src/sql_types.rs
No issue to closes
changes to query_planner to resolve columns to ids
no
no changes
=> prepare query_planner to use plan to create data flow

Cargo.lock, src/ast/Cargo.toml, src/data_manager/Cargo.toml, src/query_executor/Cargo.toml, src/query_executor/src/dml/select.rs
Closes #201 
* sends projection of columns one by one
* simple data flow that is based on `Iterator` trait
no
no
=> single table dataflow based on iterator

.github/workflows/compatibility-tests.yml, Dockerfile, build.gradle, tests/compatibility/src/test/groovy/io/database/ContainersSpecification.groovy, tests/compatibility/src/test/resources/logback-test.xml
no issue to closes
use testcontainers only locally
no
no
=> setup compatibility ci

.github/workflows/merge.yaml
=> remove functional tests job

Cargo.lock, src/data_manager/src/lib.rs, src/data_manager/src/tests/persistence.rs, src/metadata/Cargo.toml, src/metadata/src/lib.rs, src/node/src/node.rs, src/plan/src/lib.rs, src/query_analyzer/src/lib.rs, src/query_executor/src/ddl/drop_table.rs, src/query_executor/src/dml/select.rs, src/query_planner/src/create_schema.rs, src/query_planner/src/create_table.rs, src/query_planner/src/delete.rs, src/query_planner/src/drop_schema.rs, src/query_planner/src/drop_tables.rs, src/query_planner/src/insert.rs, src/query_planner/src/select.rs, src/query_planner/src/tests/delete.rs, src/query_planner/src/tests/drop_table.rs, src/query_planner/src/tests/insert.rs, src/query_planner/src/tests/select.rs, src/query_planner/src/tests/update.rs, src/query_planner/src/tests/where_clause.rs, src/query_planner/src/update.rs
Closes #372 
`DataDefinition` is fully responsible for `definition_schema` now
no
no changes
=> implement MetadataView for DataDefinition

Cargo.lock, deny.toml, src/data_manager/Cargo.toml, src/data_manager/src/lib.rs, src/description/src/lib.rs, src/meta_def/src/lib.rs, src/metadata/Cargo.toml, src/metadata/src/lib.rs, src/node/Cargo.toml, src/node/src/query_engine/mod.rs, src/node/src/query_engine/tests/extended_query_flow.rs, src/parser/src/lib.rs, src/protocol/src/pgsql_types.rs, src/query_analyzer/Cargo.toml, src/query_analyzer/src/lib.rs, src/query_executor/src/dml/insert.rs, src/sql_model/src/sql_errors.rs, src/storage/Cargo.toml, src/storage/src/in_memory.rs, src/storage/src/persistent.rs, tests/compatibility/src/test/groovy/io/database/extended/BasicQueryOperationsSpec.groovy
Closes #373 
change chashmap with dashmap
introduce first version of insert query analysis to support extended query PG protocol
no
no
=> introduce describtion flow for insert statement

src/protocol/src/hand_shake/mod.rs, src/protocol/src/hand_shake/state.rs, src/protocol/src/lib.rs
related to #377
simplification in PG protocol state machine transformation between stages
no
=> Simplify protocol hand shake state management

src/protocol/src/hand_shake/mod.rs, src/protocol/src/hand_shake/state.rs, src/protocol/src/lib.rs, src/protocol/src/messages.rs, src/protocol/src/tests/connection.rs, src/protocol/src/tests/pg_frontend.rs
Related to #377 
reduces number of state for hand_shake process in for PG protocol
no
no changes
=> reduce number of state for protocol hand shake

src/protocol/src/hand_shake/mod.rs, src/protocol/src/hand_shake/state.rs, src/protocol/src/lib.rs, src/protocol/src/message_decoder/mod.rs, src/protocol/src/message_decoder/state.rs, src/protocol/src/messages.rs
related #377
implement front end message decoding as a state machine
no
no
=> Message decoder state machine

src/protocol/src/message_decoder/mod.rs, src/protocol/src/message_decoder/state.rs
=> addition to message decoder state

Cargo.lock, src/binder/Cargo.toml, src/connection/Cargo.toml, src/connection/src/lib.rs, src/description/Cargo.toml, src/node/Cargo.toml, src/node/src/query_engine/mod.rs, src/node/src/query_engine/tests/extended_query_flow.rs, src/node/src/query_engine/tests/simple_prepared_statement.rs, src/pg_model/Cargo.toml, src/pg_model/src/lib.rs, src/pg_model/src/statement.rs, src/plan/Cargo.toml, src/query_executor/Cargo.toml, src/sql_model/Cargo.toml, tests/compatibility/src/test/groovy/io/database/extended/BasicQueryOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/database/extended/SelectiveAttributesQueryOperationsSpec.groovy
fix handling zero OID to parse prepared statement
no
no
=> fix zero OID parse prepared statement

src/node/src/query_engine/mod.rs, src/node/src/query_engine/tests/mod.rs, src/node/src/query_engine/tests/simple_prepared_statement.rs, src/plan/src/lib.rs, src/query_executor/src/lib.rs, src/query_planner/src/drop_schema.rs, src/query_planner/src/drop_tables.rs, src/query_planner/src/lib.rs, tests/compatibility/src/test/groovy/io/database/schemas/WorkingWithSchemasSpec.groovy, tests/compatibility/src/test/groovy/io/database/tables/WorkingWithTablesSpec.groovy
Closes #383
support `DROP IF EXSITS` multiple tables and schemas
yes, tests are added
=> drop if exusts multiple schemas tables

src/description/src/lib.rs, src/query_analyzer/src/lib.rs, src/query_analyzer/src/tests/ddl/create_schema.rs, src/query_analyzer/src/tests/ddl/mod.rs
add `CREATE SCHEMA` queries analysis
no
no
=> create schema query analyzer

src/description/src/lib.rs, src/query_analyzer/src/lib.rs, src/query_analyzer/src/tests/ddl/create_schema.rs, src/query_analyzer/src/tests/ddl/create_table.rs, src/query_analyzer/src/tests/ddl/drop_statements.rs, src/query_analyzer/src/tests/ddl/mod.rs
analysis of `DROP SCHEMA | TABLE` queries
no
=> drop schemas tables queries analysis

Cargo.toml, src/data_manager/src/lib.rs, src/data_manager/src/tests/persistence.rs, src/data_manager/src/tests/schema.rs, src/description/src/lib.rs, src/metadata/src/lib.rs, src/query_analyzer/src/lib.rs, src/query_analyzer/src/tests/mod.rs, src/query_analyzer/src/tests/select.rs, src/query_executor/src/dml/update.rs, src/query_planner/src/insert.rs, src/query_planner/src/select.rs, src/query_planner/src/update.rs
No issue to close. Related to #402 
select query analysis with columns
no
no changes
=> partial select analysis

.github/workflows/merge.yaml, .github/workflows/pull-requests.yml, src/binder/src/lib.rs, src/data_definition/src/lib.rs, src/data_manager/src/lib.rs, src/parser/src/lib.rs
No issue to close.
Due to heavy refactoring and redesign of sql engine GH jobs to publish docker image and run compatibility tests are skipped.
=> skip publishing ocker image on merge to master and compatibility tests on PR submission

.github/workflows/merge.yaml, .github/workflows/release.yml, CONTRIBUTING.md, Cargo.lock, Dockerfile, README.md, ci/erlang_client.sh, data/catalog/Cargo.toml, deprecated/catalog_deprecated/storage/Cargo.toml, docs/user-guide/README.md, docs/user-guide/getting_started.md, server/node/Cargo.toml, settings.gradle, tests/compatibility/src/test/groovy/io/isomorphicdb/SetupEnvironment.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/ThreeSmallIntColumnTable.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/extended/BasicQueryOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/extended/SelectiveAttributesQueryOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/parser/ParsingErrorSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/schemas/WorkingWithSchemasSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/simple/BasicQueryOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/simple/PreparedStatementOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/simple/SelectiveAttributesQueryOperationsSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/tables/WorkingWithTablesSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/types/BooleanConstraintsChecksSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/types/IntegerConstraintsChecksSpec.groovy, tests/compatibility/src/test/groovy/io/isomorphicdb/types/StringsConstraintsChecksSpec.groovy
replacing `database` with new name `isomorphicdb` wherever appropriate
ha-ha no 😄 
no changes
=> replace database with isomorphicdb wherever appropriate

data/catalog/src/in_memory.rs, data/catalog/src/lib.rs, data_manipulation/query_result/src/lib.rs, data_manipulation/typed_queries/src/lib.rs, server/node/src/query_engine/mod.rs, server/node/src/query_engine/tests/mod.rs, write_query/executor/src/lib.rs
delete all records queries are handled with new query engine
no
no changes to output
=> use new query engine to delete all records from table

src/data_manipulation/operators/src/lib.rs, src/data_manipulation/typed_tree/src/lib.rs, src/data_manipulation/typed_tree/src/tests/unary_op.rs, src/data_manipulation/untyped_tree/src/lib.rs, src/query_analyzer/src/operation_mapper.rs, src/query_analyzer/src/tests/insertions/expressions.rs, src/query_analyzer/src/tests/mod.rs, src/query_analyzer/src/tests/operation_mapping.rs, src/query_processing/type_inference/src/tests/operations.rs
Closes #494 
added support of `~` operator
=> Add support for unary bitwise not operator

src/data_manipulation/operators/src/lib.rs, src/data_manipulation/query_result/src/lib.rs, src/data_manipulation/typed_tree/src/lib.rs, src/data_manipulation/typed_tree/src/tests/unary_op.rs, src/pg_result/src/lib.rs
Closes #495 Closes #496 
Added support for unary square and cube root operators
=> Added support for unary square and cube root operators

src/data_manipulation/operators/src/lib.rs, src/data_manipulation/typed_tree/src/lib.rs, src/data_manipulation/typed_tree/src/tests/unary_op.rs
Closes #497 Closes #498 
Added support for factorial and abs unary operators
=> Added support for factorial and abs unary operators

src/data_manipulation/operators/src/lib.rs, src/data_manipulation/typed_tree/src/tests/binary_ops/bitwise.rs, src/data_manipulation/typed_tree/src/tests/binary_ops/mod.rs, src/data_manipulation/typed_tree/src/tests/mod.rs, src/data_manipulation/typed_tree/src/tests/unary_op.rs, src/server/node/src/query_engine/tests/insert.rs
Closes #505 
Closes #512
Closes #513 
Closes #514 
added initial support for binary bitwise operators
=> Add support for binary bitwise operators

src/data_manipulation/operators/src/lib.rs, src/data_manipulation/typed_tree/src/tests/binary_ops/comparison.rs, src/data_manipulation/typed_tree/src/tests/binary_ops/mod.rs
Closes #509 
Closes #489 
add support for binary comparison operators
=> Add support for binary comparison operators

src/data/catalog/src/in_memory/mod.rs, src/data/catalog/src/in_memory/tests/mod.rs, src/data/catalog/src/lib.rs, src/data_manipulation/typed_tree/src/lib.rs, src/data_manipulation/untyped_tree/src/lib.rs, src/query_analyzer/src/dynamic_tree_builder.rs, src/query_analyzer/src/tests/selects/expressions.rs, src/query_analyzer/src/tests/updates/expressions.rs, src/query_processing/type_inference/src/lib.rs, src/server/node/src/query_engine/mod.rs, src/server/node/src/query_engine/tests/update.rs, src/write_query/executor/src/lib.rs
evaluate `DynamicTypedTree` as `StaticTypedTree`
=> support evaluation of dynamic operation trees

Cargo.lock, src/catalog/src/in_memory/mod.rs, src/catalog/src/lib.rs, src/data/binary/src/repr.rs, src/data_manipulation/query_plan/Cargo.toml, src/data_manipulation/query_plan/src/lib.rs, src/data_manipulation/query_result/src/lib.rs, src/data_manipulation/typed_values/Cargo.toml, src/data_manipulation/typed_values/src/lib.rs, src/entities/types/src/lib.rs, src/pg_result/src/lib.rs, src/query_planner/Cargo.toml, src/query_planner/src/lib.rs, src/server/node/src/query_engine/tests/mod.rs, src/server/node/src/query_engine/tests/type_constraints.rs
Closes #529 
implement insert query plan (without taking into account other query types)
=> expand insert query plan

Cargo.lock, src/catalog/src/in_memory/data_catalog.rs, src/catalog/src/in_memory/mod.rs, src/catalog/src/lib.rs, src/data_manipulation/query_plan/Cargo.toml, src/data_manipulation/query_plan/src/lib.rs, src/query_planner/src/lib.rs, src/server/node/src/query_engine/mod.rs
Closes #532
implement `DeleteQueryPlan`
=> implement delete query plan

postgres/query_ast/src/lib.rs, postgres/query_parser/src/lib.rs, postgres/query_parser/src/tests/insert.rs, sql_engine/data_manipulation/typed_values/src/lib.rs, sql_engine/query_analyzer/src/dynamic_tree_builder.rs, sql_engine/query_analyzer/src/operation_mapper.rs, sql_engine/query_analyzer/src/static_tree_builder.rs, sql_engine/query_analyzer/src/tests/operation_mapping.rs, src/query_engine/tests/insert.rs, src/query_engine/tests/update.rs
enable test for unary and binary operators
=> implement unary operators parsing

postgres/query_response/src/lib.rs, sql_engine/data_manipulation/query_plan/src/lib.rs, sql_engine/data_manipulation/query_result/src/lib.rs, src/query_engine/tests/mod.rs, src/query_engine/tests/type_constraints.rs
=> enable type constraint tests

docs/RFCs/text/2021-04-24-Executing-Multiple-Queries-In-Single-Transaction.md
[rendered](https://github.com/alex-dukhno/isomorphicdb/blob/ac9713a673f27a1455563a9f513fafd384bd7c96/docs/RFCs/text/2021-04-24-Executing-Multiple-Queries-In-Single-Transaction.md)
=> [RFC] Executing multiple queries in single transaction

.github/workflows/java-drivers-compatibility-tests.yml, .github/workflows/pgjdbc-driver.yml, .github/workflows/pgjdbc-ng-driver.yml, .github/workflows/psycopg2.yml
=> pgjdbc-ng, pgjdbc drivers and psycopg2

docs/RFCs/text/2021-05-15-Type-System.md
[Rendered](https://github.com/alex-dukhno/isomorphicdb/blob/ce5f4e8caaed4061147fffbb600b72a932469328/docs/RFCs/text/2021-05-15-Type-System.md)
=> [RFC] implementing type system
