alex-dukhno/isomorphicdb

src/node/src/node.rs
src/sql_engine/src/lib.rs
src/storage/src/frontend/mod.rs
src/storage/src/lib.rs

Fixes #70 
Tests with unit-tests and `psql` as below.
```
asongala=> create schema schema_name;
CREATE SCHEMA
asongala=> create table schema_name.table_name (column_in_table smallint);
CREATE TABLE
asongala=> select column_not_in_table from schema_name.table_name;
ERROR:  column "column_not_in_table" does not exist
```

Handle the error when user selects non-existing columns in the table

---

src/sql_engine/src/lib.rs
src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/queries/update.rs

Fixes #72 
1. Handles updating specified columns of all records.
```
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name values (111, 222, 333);
INSERT 0 1
xxx=> insert into schema_name.table_name values (444, 555, 666);
INSERT 0 1
xxx=> select * from schema_name.table_name;
col1 | col2 | col3 
------+------+------
111 |  222 |  333
444 |  555 |  666
(2 rows)
xxx=> update schema_name.table_name set col3=777, col1=999;
UPDATE 2
xxx=> select * from schema_name.table_name;
col1 | col2 | col3 
------+------+------
999 |  222 |  777
999 |  555 |  777
(2 rows)
```
2. Returns an error if the updated column is not …

Handle updating specified columns of all records and return an error if the updated column is not existing

---

src/sql_engine/src/lib.rs
src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/mod.rs
src/storage/src/frontend/tests/queries/delete.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/select.rs
src/storage/src/frontend/tests/queries/update.rs

Fixes #103 
```
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name (col3, col2, col1) values (1, 2, 3);
INSERT 0 1
xxx=> insert into schema_name.table_name (col3, col2, col1) values (4, 5, 6);
INSERT 0 1
xxx=> select * from schema_name.table_name;
col1 | col2 | col3
------+------+------
3 |    2 |    1
6 |    5 |    4
(2 rows)
```
Our current implementation: I sets an integer `0` for the default value.
```
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name (col3, col2) …
```

 Handling named columns insertion

---

src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/update.rs
src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/update.rs
src/storage/src/lib.rs

Changed the ConstraintViolations variant of QueryError to contain a vector of all ConstraintErrors that occurred during query execution. This change was to maintain the order of errors as they occur.
Resolves #148

Constraint error order

---

src/protocol/src/results.rs
src/sql_engine/src/ddl/create_table.rs
src/sql_engine/src/tests/insert.rs
src/sql_types/src/lib.rs
src/storage/src/frontend/tests/queries/delete.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/select.rs
src/storage/src/frontend/tests/queries/update.rs
src/storage/src/frontend/tests/schema.rs
src/storage/src/frontend/tests/table.rs

Closes #96
Please give your input @alex-dukhno!

Support serial data types.

---

src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/queries/insert.rs

Resolves #153 
This PR changes how errors are reported during an insert operation. When a constraint violation occurs during inserting the current row is finished and the remaining rows are ignored.
Update behavior was not changed.
What are your thoughts?

Abort insert when constraint error occurs.

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/merge.yaml
src/protocol/src/lib.rs
src/protocol/src/results.rs
src/protocol/src/sql_types.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/update.rs
src/sql_types/src/lib.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/update.rs

updates message for constraint violations
```
xxx=> insert into schema_n.tab1 values ('123456', 123.4);
ERROR:  smallint out of range
ERROR:  invalid input syntax for type smallint: "123.4"
xxx=> insert into schema_n.tab values ('123456');
ERROR:  value too long for type character(5)
```

update constraints error messages

---

tests/functional/basic_queries_tests.py
tests/functional/queries_with_sql_types.py

1 - try-except blocks were removed. we shouldn't use them with PyTest
2 - some execute rows were changed to executemany
3 - annotation types were added, so method resolution will work inside of user test functions

Functional tests

---

src/sql_engine/src/ddl/create_table.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs
src/sql_engine/src/tests/insert.rs
src/sql_engine/src/tests/mod.rs
src/sql_engine/src/tests/schema.rs
src/sql_engine/src/tests/table.rs
src/sql_engine/src/tests/type_constraints.rs
src/sql_types/src/lib.rs
src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/mod.rs
src/storage/src/frontend/tests/queries/delete.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/select.rs
src/storage/src/frontend/tests/queries/update.rs
src/storage/src/frontend/tests/schema.rs
src/storage/src/lib.rs

Ongoing work
PR introduces `ColumnDefinition` struct with `name` and `sql_type` to work with instead of `(String, SqlType)` tuple
Nothing is changed

added column definition struct

---

Cargo.lock
src/protocol/src/lib.rs
src/protocol/src/listener.rs
src/protocol/src/results.rs
src/sql_engine/Cargo.toml
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/tests/insert.rs

Does not close any issue, however, it is a part of #127 
PR adds code to evaluate **supported** math expression for integers and concatenation for strings
* by supported I mean that some operators are not supported by https://github.com/ballista-compute/sqlparser-rs
```
psql (12.2, server 0.0.0)
alex-dukhno=> create schema schema_name;
CREATE SCHEMA
alex-dukhno=> create table schema_name.table_name (s smallint);
CREATE TABLE
alex-dukhno=> insert into schema_name.table_name values (10 + 20 * 2 - 30 / 3);
INSERT 0 1
alex-dukhno=> select * from schema_name.table_name;
s
----
40
(1 row)
alex-dukhno=> insert into schema_name.table_name values (10 || 20);
ERROR:  operator does not exist: (NUMBER || NUMBER)
```

math expression with integers and strings concatenation evaluation in insert queries

---

src/storage/src/frontend/tests/mod.rs
src/storage/src/frontend/tests/queries/delete.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/select.rs
src/storage/src/frontend/tests/queries/update.rs
src/storage/src/frontend/tests/schema.rs
src/storage/src/frontend/tests/table.rs

Closes #141 
* Added fixture for `default_schema_name`, which is `"schema_name"`. 
* Added fixture for `storage_with_schema` that initialize storage with `default_schema_name`.
* Updated tests in `Frontend` to use new introduced fixtures.
* Should we add fixture`default_table_name` for `"table_name"`? It's duplicated all over the place.
* Might be useful to add fixtures for different types of columns. Instead of having fixtures for concrete tables (like [`storage_with_ints_table`](https://github.com/alex-dukhno/database/blob/master/src/storage/src/frontend/tests/queries/update.rs#L103)), I would rather have something like:
```
#[rstest::fixture]
fn ints_columns() -> Vec<(&str, SqlType)> {
vec![
("column_si", SqlType::SmallInt(i16::min_value())),
("column_i", …
```

Frontend Storage tests improvements (#141)

---

src/node/src/node.rs
src/node/src/query_listener.rs
src/protocol/src/lib.rs
src/protocol/src/listener.rs
src/protocol/src/messages.rs

Closes #172 
1. Adds abstract Trait `Channel` for both TCP and TLS streams.
1. Moves major Server associating code from `protocol` to `node`.
1. Deletes `QueryListener` method `handle_connection`. Since the connection returns from `accept` to `node`. (We will think about and implement callback function `handle_command` later).
1. Improves some code based on PR #171 and #175 .

Implement abstract Channel for both TCP and TLS

---

src/node/src/node.rs
src/protocol/src/lib.rs
src/sql_engine/src/ddl/create_schema.rs
src/sql_engine/src/ddl/drop_schema.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/query/mod.rs
src/sql_engine/src/query/plan.rs
src/sql_engine/src/query/transform.rs
src/sql_engine/src/tests/in_memory_backend_storage.rs
src/sql_engine/src/tests/mod.rs
src/sql_engine/src/tests/schema.rs
src/storage/src/backend.rs
src/storage/src/frontend/mod.rs

extracts `QueryProcessor` from #183 (there it called `QueryTransform`)
changes `create schema` and `drop schema` queries to use new `QueryProcessor`
no changes to output

migrate create and drop schema to QueryProcessor

---

src/sql_types/src/lib.rs
src/storage/src/frontend/mod.rs

Closes #114 
Implemented the ability to query the 'system.columns' table to get a list of columns.
```
vkulichenko=> create schema schema_name;
CREATE SCHEMA
vkulichenko=> create table schema_name.table_name (col_1 smallint, col_2 integer, col_3 bigint);
CREATE TABLE
vkulichenko=> create schema schema_name;
ERROR:  schema "schema_name" already exists
vkulichenko=> select * from system.columns;
schema_name | table_name | column_name | column_type 
-------------+------------+-------------+-------------
schema_name | table_name | col_1       | SMALLINT
schema_name | table_name | col_2       | INT
schema_name | table_name | col_3       | BIGINT
(3 rows)
```

SQL API for system tables (#114)

---

src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs
src/sql_engine/src/query/expr.rs
src/sql_engine/src/query/mod.rs
src/sql_engine/src/query/repr.rs
src/sql_engine/src/query/tests.rs
src/sql_engine/src/query/transform.rs
src/sql_engine/src/tests/insert.rs
src/sql_engine/src/tests/schema.rs
src/sql_engine/src/tests/select.rs
src/sql_engine/src/tests/table.rs
src/sql_engine/src/tests/type_constraints.rs
src/sql_engine/src/tests/update.rs
src/storage/src/frontend/mod.rs
src/storage/src/lib.rs

I as I wrote in https://github.com/alex-dukhno/database/pull/199#issuecomment-663103117
this PR is targeting `migrate-insert` branch not master.
As I can see I was able to resurrect most of cases the following is left:

almost working updates is left, I hope

---

src/representation/src/lib.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/query/mod.rs
src/sql_engine/src/query/plan.rs
src/sql_engine/src/query/process.rs
src/sql_engine/src/tests/in_memory_backend_storage.rs
src/storage/src/backend.rs
src/storage/src/frontend/mod.rs
src/storage/src/frontend/tests/mod.rs
src/storage/src/frontend/tests/queries/delete.rs
src/storage/src/frontend/tests/queries/insert.rs
src/storage/src/frontend/tests/queries/select.rs

No issue to close. Work done under #188 
Simplistic representation of `TableInserts` for `InsertCommand` just to reduce number of parameters to `new()` constructor.
Removes methods from `QueryProcessor` and adds `TryFrom<ObjectName>` implementations for `SchemaId` and `TableId`
change `Row` type alias to `(Binary, Binary)` instead of `(Vec<u8>, Vec<u8>)`
No notable changes

simplistic insert migration to query processor

---

Cargo.lock
src/node/Cargo.toml
src/node/src/node.rs

The latest code is crashed when running with command `psql -h localhost -W` (after inputting the password).
The cash log is outputted as below.
```
...
Running `target/debug/database`
thread 'main' panicked at '`Task::spawn()` must be called from an `Executor` or `LocalExecutor`', /rustc/c367798cfd3817ca6ae908ce675d1d99242af148/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This crash is caused by upgrading crate `smol` in PR #224 . It works when downgrading to `smol-0.2.0`.
It seems that `smol::Task` must be called in smol `Executor` or `LocalExecutor` from `0.3`.
The command `psql -h localhost -W` could work when fixing to use `smol::block_on`.

Fix crash for upgrading crate smol

---

src/node/src/node.rs
src/protocol/src/lib.rs
src/protocol/src/messages.rs
src/protocol/src/results.rs
src/protocol/src/tests/connection.rs
src/protocol/src/tests/hand_shake.rs

This PR is part of Issue #177  (should not close).
Adds Frontend Messages to separate with Backend Messages, and decodes Frontend Messages from incoming data, including Extended Query.
In PostgreSQL there are two ways to construct prepared statements:
1. Via an explicit user-provided `PREPARE <statement name> AS <SQL>` SQL statement.
https://www.postgresql.org/docs/current/sql-prepare.html
https://www.postgresql.org/docs/current/sql-execute.html
https://www.postgresql.org/docs/current/sql-deallocate.html
2. Via Extended Query as part of the Frontend/Backend Messages.
https://www.postgresql.org/docs/12/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY
For SQL statements `PREPARE`, `EXECUTE` and `DEALLOCATE`, they could be easily tested (via `psql` or `psycopg2`). But I could not find a good …

Decode Frontend Messages

---

.gitignore
Cargo.lock
src/node/src/node.rs
src/sql_engine/src/catalog_manager/data_definition.rs
src/sql_engine/src/catalog_manager/mod.rs
src/storage/Cargo.toml
src/storage/src/persistent.rs
src/storage/src/tests/persistent.rs

Closes #38 
database use on disk persistence if it is run with `PERSISTENT=1` env variable
user can work with previous dataset if start database with the following command `PERSISTENT=1 RUST_LOG=debug cargo run`
```
$ psql -h 127.0.0.1 -W
Password:
psql (12.3, server 0.0.0)
alex-dukhno=> create schema schema_name;
CREATE SCHEMA
alex-dukhno=> create table schema_name.table_name (col1 integer);
CREATE TABLE
alex-dukhno=> insert into schema_name.table_name values (1);
INSERT 0 1
alex-dukhno=> select * from schema_name.table_name;
col1
------
1
(1 row)
alex-dukhno=> \q
```
after quitting `psql` and reconnecting to database
```
psql -h 127.0.0.1 -W
Password:
psql (12.3, server 0.0.0)
alex-dukhno=> select * from schema_name.table_name;
col1
------
1 …
```

preserve data after database instance restart

---

src/protocol/src/results.rs
src/sql_engine/src/catalog_manager/data_definition.rs
src/sql_engine/src/catalog_manager/mod.rs
src/sql_engine/src/catalog_manager/tests/mod.rs
src/sql_engine/src/catalog_manager/tests/queries/delete.rs
src/sql_engine/src/catalog_manager/tests/queries/select.rs
src/sql_engine/src/catalog_manager/tests/schema.rs
src/sql_engine/src/catalog_manager/tests/table.rs
src/sql_engine/src/ddl/drop_schema.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/query/plan.rs
src/sql_engine/src/query/process.rs
src/storage/src/in_memory.rs
src/storage/src/lib.rs
src/storage/src/persistent.rs
src/storage/src/tests/in_memory.rs
src/storage/src/tests/persistent.rs

Closes #252 
added support for `drop schema schema_name [restrict|cascade]`
```
alex-dukhno=> create schema schema_name;
CREATE SCHEMA
alex-dukhno=> create table schema_name.table_name (col1 integer);
CREATE TABLE
alex-dukhno=> insert into schema_name.table_name values (1);
INSERT 0 1
alex-dukhno=> select * from schema_name.table_name;
col1
------
1
(1 row)
alex-dukhno=> drop schema schema_name cascade;
DROP SCHEMA
alex-dukhno=> select * from schema_name.table_name;
ERROR:  schema "schema_name" does not exist
```

implement drop schema cascade

---

src/protocol/src/lib.rs
src/protocol/src/results.rs
src/sql_engine/src/ddl/drop_schema.rs
src/sql_engine/src/dml/delete.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/mod.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/query/process.rs
src/sql_engine/src/tests/delete.rs
src/sql_engine/src/tests/describe_prepared_statement.rs
src/sql_engine/src/tests/insert.rs
src/sql_engine/src/tests/mod.rs
src/sql_engine/src/tests/parse.rs
src/sql_engine/src/tests/schema.rs
src/sql_engine/src/tests/select.rs
src/sql_engine/src/tests/table.rs
src/sql_engine/src/tests/type_constraints.rs
src/sql_engine/src/tests/update.rs

Closes #200
`QueryError` represents single error

make QueryError represent single error

---

src/sql_engine/src/catalog_manager/data_definition.rs
src/sql_engine/src/catalog_manager/mod.rs
src/sql_engine/src/catalog_manager/tests/schema.rs
src/sql_engine/src/ddl/drop_schema.rs
src/sql_engine/src/query/process.rs

no issue to closes
`CatalogManager::drop_schema` requires u64 schema id instead of name
no changes to output

drop shema by id

---

src/sql_engine/src/catalog_manager/mod.rs
src/sql_engine/src/catalog_manager/tests/persistence.rs
src/sql_engine/src/catalog_manager/tests/schema.rs
src/sql_engine/src/catalog_manager/tests/table.rs
src/sql_engine/src/ddl/create_schema.rs
src/sql_engine/src/ddl/create_table.rs
src/sql_engine/src/ddl/drop_schema.rs
src/sql_engine/src/ddl/drop_table.rs
src/sql_engine/src/dml/delete.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs

`CatalogManager::drop_table` uses `u64` schema and table ids

drop table with schema and table id

---

src/sql_engine/src/catalog_manager/mod.rs
src/sql_engine/src/catalog_manager/tests/persistence.rs
src/sql_engine/src/catalog_manager/tests/queries/delete.rs
src/sql_engine/src/catalog_manager/tests/queries/select.rs
src/sql_engine/src/dml/delete.rs
src/sql_engine/src/dml/insert.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/dml/update.rs

migrate `CatalogManager::write_to`, `CatalogManager::full_scan` and `CatalogManager::drop_from` to use `u64` schema and table id

migrate write_to, full_scan and drop_from to use schema and table id

---

src/protocol/src/lib.rs
src/protocol/src/session.rs
src/protocol/src/statement.rs
src/sql_engine/src/ddl/drop_table.rs
src/sql_engine/src/lib.rs

abstract away `PreparedStatement` from `sqlparser`

generalise and move prepared_statement to protocol

---

src/sql_engine/src/lib.rs
src/sql_engine/src/tests/error_responses.rs
src/sql_engine/src/tests/mod.rs

As @alex-dukhno mentioned, `psql` is stuck after inputting wrong SQL syntax (as `selec * from table`).
Fixes to always return `ReadyForQuery` message (as `QueryEvent::QueryComplete`) after both `CommandComplete` or `ErrorResponse` messages. I missed to return `ReadyForQuery` after `ErrorResponse` before.
After adding this fix, the `psql` could display the error message without stuck.
```
xxx=> selec * from table;
ERROR:  syntax error in "selec * from table;" can't be parsed
```

Fix to always return ReadyForQuery after an ErrorResponse

---

src/ast/src/lib.rs
src/expr_eval/src/dynamic_expr.rs
src/expr_eval/src/tests/dynamic_expressions.rs
src/sql_engine/src/dml/update.rs
src/sql_engine/src/tests/type_constraints.rs
tests/functional/test_queries_with_sql_types.py

Closes #313 
`DynamicExpressionEvaluation::eval` returns `ScalarOp` which then casted to column type and converted into `Datum`. That helps when updates involves columns with different types
```
alex-dukhno=> create schema schema_name;
CREATE SCHEMA
alex-dukhno=> create table schema_name.table_name(si_col smallint, i_col integer);
CREATE TABLE
alex-dukhno=> insert into schema_name.table_name values (10000, 50000);
INSERT 0 1
alex-dukhno=> insert into schema_name.table_name values (1000, 500000);
INSERT 0 1
alex-dukhno=> select * from schema_name.table_name;
si_col | i_col
--------+--------
10000 |  50000
1000 | 500000
(2 rows)
alex-dukhno=> update schema_name.table_name set i_col = 2 * si_col + i_col;
UPDATE 2
alex-dukhno=> select * from schema_name.table_name;
si_col | …
```

dynamic expression evaluates to ScalarOp instead of Datum

---

src/protocol/src/results.rs
src/query_planner/src/planner/insert.rs
src/query_planner/src/planner/update.rs

Fixes regression of when same column name occurs multiple times in insert and update assignments
```
alex-dukhno=> insert into s.t (i, i) values (1, 2);
ERROR:  column "i" specified more than once
alex-dukhno=> update s.t set i = 2 + i, i = 2 * i;
ERROR:  syntax error: multiple assignments to same column "i"
```

Fixes regression of when same column name occurs multiple times in insert and update assignments

---

.github/PULL_REQUEST_TEMPLATE.md
Cargo.lock
src/ast/src/values.rs
src/data_manager/Cargo.toml
src/protocol/src/lib.rs
src/protocol/src/messages.rs
src/protocol/src/results.rs
src/sql_engine/src/dml/select.rs
src/sql_engine/src/lib.rs
src/sql_engine/src/tests/bind_prepared_statement_to_portal.rs
src/sql_engine/src/tests/delete.rs
src/sql_engine/src/tests/describe_prepared_statement.rs
src/sql_engine/src/tests/error_responses.rs
src/sql_engine/src/tests/execute_portal.rs
src/sql_engine/src/tests/insert.rs
src/sql_engine/src/tests/mod.rs
src/sql_engine/src/tests/parse_prepared_statement.rs
src/sql_engine/src/tests/schema.rs
src/sql_engine/src/tests/select.rs
src/sql_engine/src/tests/table.rs
src/sql_engine/src/tests/type_constraints.rs
src/sql_engine/src/tests/update.rs

remove allocation in `QueryEvent` mapping to `BackendMessage`
change assertion on received query events
no
no changes

QueryEvent maps to single BackendMessage

---

Cargo.lock
deny.toml
src/node/src/node.rs
src/protocol/Cargo.toml
src/protocol/src/lib.rs
src/protocol/src/messages.rs
src/protocol/src/tests/accept_client_request.rs
src/protocol/src/tests/connection.rs
src/protocol/src/tests/hand_shake.rs
src/protocol/src/tests/mod.rs
src/protocol/src/tests/pg_frontend.rs

Implements the Protocol part of #207.
This PR only implements the Protocol of `CancelRequest`. In-progress query cancellation hasn't been implemented yet.
1. Adds struct `ConnSupervisor` to save the all current active connection pairs - `conn_id` and `secret_key`. The `secret_key` needs to be verified when invoking `CancelRequest` from another new connection.
2. Returns `conn_id` and `secret_key` in backend message `BackendKeyData` (before `ReadyForQuery`) when startup.
Since the in-progress query cancellation hasn't been supported, the Empty cancellation could only been tested via `psycopg2` (in `python` command line).
```
ipython
In [1]: from psycopg2 import connect
In [2]: conn = connect(host="localhost", password="check_this_out", database="postgres")
In [3]: conn.cancel()
```
The …

Implement query cancellation for PostgreSQL wire protocol

---

Cargo.lock
src/ast/src/lib.rs
src/ast/src/predicates.rs
src/node/src/query_engine/mod.rs
src/node/src/query_engine/tests/mod.rs
src/node/src/query_engine/tests/where_clause.rs
src/plan/Cargo.toml
src/plan/src/lib.rs
src/query_executor/src/dml/select.rs
src/query_planner/Cargo.toml
src/query_planner/src/select.rs
src/query_planner/src/tests/mod.rs
src/query_planner/src/tests/select.rs
src/query_planner/src/tests/where_clause.rs

Related to #290 
added `Filter` dataflow element to experiment with `where` predicate inside `select` queries
yes, but experimental
```
alex-dukhno=> create schema s;
CREATE SCHEMA
alex-dukhno=> create table t (c1 smallint, c2 smallint, c3 smallint);
ERROR:  syntax error: unsupported table name 't'. All table names must be qualified
alex-dukhno=> create table s.t (c1 smallint, c2 smallint, c3 smallint);
CREATE TABLE
alex-dukhno=> insert into s.t values (1, 2, 3), (4, 5, 6), (7, 8, 9);
INSERT 0 3
alex-dukhno=> select * from s.t where c1 = 1;
c1 | c2 | c3
----+----+----
1 |  2 |  3
(1 row)
alex-dukhno=> select * from s.t where c1 = 2;
c1 | c2 | c3
----+----+----
(0 rows)
alex-dukhno=> select * from s.t where c1 = 4;
c1 | c2 | c3
----+----+----
4 |  5 |  6
(1 row)
```

experimental filter dataflow element

---

Cargo.lock
src/protocol/src/lib.rs
src/protocol/src/tests/connection.rs

Closes #354 
This issue occurred when client disconnected immediately without sending a `Terminate` message.
As client closed the socket directly, the server side could only receive a zero byte for client close.
no
This issue could be reproduced as @alex-dukhno 's comment in #354 when running compatibility tests, or run the below `groovy` script.
```
groovysh
groovy:000>
:grab org.postgresql:postgresql:9.4-1205-jdbc42
import groovy.sql.Sql
dbConf = [
url: "jdbc:postgresql://localhost:5432/test?gssEncMode=disable&sslmode=disable&preferQueryMode=extendedForPrepared",
user: "postgres",
password: "postgres",
driver: "org.postgresql.Driver",
]
db = Sql.newInstance(dbConf)
```
Then exit directly as below (or `CTRL + C`) without calling `db.close()`.
```
groovy:000>:exit
```
The log message …

Fix the issue of reporting UnexpectedEof when client disconnected immediately

---

Cargo.lock
src/expr_eval/Cargo.toml
src/expr_eval/src/dynamic_expr.rs
src/expr_eval/src/lib.rs
src/expr_eval/src/static_expr.rs
src/expr_eval/src/tests/dynamic_expressions.rs
src/expr_eval/src/tests/mod.rs
src/expr_eval/src/tests/static_expressions.rs
src/protocol/src/tests/accept_client_request.rs
src/query_executor/src/dml/insert.rs
src/query_executor/src/dml/update.rs

No issue to close, related to #352 
`protocol::{Sender, result::QueryError}` from `expr_eval` module
no
no changes

remove protocol dependency from expr_eval

---

Cargo.lock
src/node/src/query_engine/mod.rs
src/parser/Cargo.toml
src/parser/src/lib.rs
src/plan/src/lib.rs
src/protocol/src/lib.rs
src/query_executor/src/lib.rs
src/query_planner/Cargo.toml
src/query_planner/src/create_schema.rs
src/query_planner/src/create_table.rs
src/query_planner/src/delete.rs
src/query_planner/src/drop_schema.rs
src/query_planner/src/drop_tables.rs
src/query_planner/src/insert.rs
src/query_planner/src/lib.rs
src/query_planner/src/select.rs
src/query_planner/src/tests/create_schema.rs
src/query_planner/src/tests/create_table.rs
src/query_planner/src/tests/delete.rs
src/query_planner/src/tests/drop_schema.rs
src/query_planner/src/tests/drop_table.rs
src/query_planner/src/tests/insert.rs
src/query_planner/src/tests/mod.rs
src/query_planner/src/tests/select.rs
src/query_planner/src/tests/update.rs
src/query_planner/src/tests/where_clause.rs
src/query_planner/src/update.rs
src/sql_model/src/sql_types.rs

remove `protocol`, `kernel` dependency from `query_planner` module
no
no

remove protocol dependency from query planner

---

src/protocol/src/tests/accept_client_request.rs
src/protocol/src/tests/async_io.rs

Closes #370 
Fixes the field `request` and `response` of `TestCase` to type `Arc<Mutex<Unblock<File>>>`.
And clones them directly in function `clone`.
No
No

Fix to combine async_dup Arc and Mutex to avoid thread issue in test

---

src/ast/src/values.rs
src/binary/src/lib.rs
src/constraints/src/lib.rs
src/data_manager/src/tests/queries.rs
src/data_manager/src/tests/schema.rs
src/data_manager/src/tests/table.rs
src/metadata/src/lib.rs
src/node/src/query_engine/tests/insert.rs
src/node/src/query_engine/tests/table.rs
src/pg_model/Cargo.toml
src/query_analyzer/src/lib.rs
src/query_planner/src/tests/create_table.rs
src/query_planner/src/tests/insert.rs
src/query_planner/src/tests/mod.rs
src/query_planner/src/tests/update.rs
src/sql_model/src/sql_types.rs

`smallserial`, `serial` and `bigserial` support are removed as they were not implemented correctly
no
yes, user can't create table with above three types

remove serial types support

---

Cargo.lock
src/ast/src/predicates.rs
src/binder/Cargo.toml
src/binder/src/lib.rs
src/query_planner/src/select.rs
src/sql_model/src/lib.rs
tests/compatibility/src/test/groovy/io/database/extended/SelectiveAttributesQueryOperationsSpec.groovy

Closes #275 
Implements Parameter Bind for simple expression on SQL Where clause as below.
```
prepare fooplan (smallint) as select * from schema_name.table_name where col1 = $1
```
Yes. Some database drivers could directly use Extended Protocol. And this PR updates the Bind logic for `Select` queries. 
```
CREATE SCHEMA
xxx=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
xxx=> insert into schema_name.table_name values (1, 2, 3);
INSERT 0 1
xxx=> prepare fooplan (smallint) as select * from schema_name.table_name where col1 = $1;
PREPARE
xxx=> execute fooplan(1);
col1 | col2 | col3
------+------+------
1 |    2 |    3
(1 row)
```

Implement Parameter Bind on SQL Where clause

---

Cargo.lock
src/ast/src/lib.rs
src/binary/Cargo.toml
src/binary/src/lib.rs
src/connection/src/lib.rs
src/description/Cargo.toml
src/description/src/lib.rs
src/metadata/Cargo.toml
src/metadata/src/lib.rs
src/node/src/query_engine/mod.rs
src/node/src/query_engine/tests/delete.rs
src/node/src/query_engine/tests/extended_query_flow.rs
src/node/src/query_engine/tests/insert.rs
src/node/src/query_engine/tests/select.rs
src/node/src/query_engine/tests/simple_prepared_statement.rs
src/node/src/query_engine/tests/type_constraints.rs
src/node/src/query_engine/tests/update.rs
src/node/src/query_engine/tests/where_clause.rs
src/pg_model/src/lib.rs
src/pg_model/src/pg_types.rs
src/pg_model/src/results.rs
src/pg_model/src/statement.rs
src/query_analyzer/src/lib.rs
src/query_analyzer/src/tests/create_table.rs
src/query_analyzer/src/tests/insert.rs
src/query_analyzer/src/tests/mod.rs
src/query_executor/src/dml/select.rs
src/repr/Cargo.toml
src/repr/src/lib.rs
src/sql_model/src/sql_types.rs

instead of having `SqlType`s with length on min/max values limits store type id and length, int range value in SYSTEM.DEFINITION_SCHEMA.DATA_TYPE_DESCROPTOR table
no

storing types in SYSTEM.DEFINITION_SCHEMA.DATA_TYPE_DESCROPTOR table

---

src/description/src/lib.rs
src/meta_def/src/lib.rs
src/node/src/query_engine/mod.rs
src/node/src/query_engine/tests/extended_query_flow.rs
src/node/src/query_engine/tests/simple_prepared_statement.rs
src/pg_model/src/results.rs
src/query_analyzer/src/lib.rs
src/query_analyzer/src/tests/insert.rs

Closes #400
Implements parameter type analysis for assign operation SQL, based on PR #407 , and handles some special `prepare` cases.
Yes, this PR handles `psql` output of some special `prepare` cases as `Postgres` response.
The below SQL should be parsed successfully by analyzing the Table description.
```
xxx=> create table schema_name.table_name (col_1 smallint, col_2 smallint);
xxx=> prepare fooplan as insert into schema_name.table_name values ($2, $1);
PREPARE
```
`psql` should report a error message of `could not determine data type of parameter $3` for the below SQL.
```
xxx=> prepare fooplan (smallint, smallint) as insert into schema_name.table_name values (1, $9);
ERROR:  could not determine data type of parameter $3
```
Since the SQL contains the …

Implement parameter type analysis for assign operation SQL of Prepared Statement

---

src/description/src/lib.rs
src/node/src/query_engine/mod.rs
src/node/src/query_engine/tests/extended_query_flow.rs
src/node/src/query_engine/tests/simple_prepared_statement.rs
src/query_analyzer/Cargo.toml
src/query_analyzer/src/lib.rs
src/query_analyzer/src/tests/mod.rs
src/query_analyzer/src/tests/update.rs

Closes #401 
Implements parameter type analysis for re-assign (Update) operation SQL.
Yes, this PR handles parameter type analysis for both `prepare` SQL of `psql` and `Parse` messages of Extended Protocol.
The below SQL should be parsed successfully by analyzing the Table description.
```
xxx=> create table schema_name.table_name (col_1 smallint, col_2 smallint);
xxx=> prepare fooplan as update schema_name.table_name set COL_2 = $1 where col_1 = $2;
PREPARE
```
For `psql`:
```
CREATE SCHEMA
xxx=> create table schema_name.table_name (col_1 smallint, col_2 smallint);
CREATE TABLE
xxx=> prepare fooplan as update schema_name.table_name set col_2 = $1 where col_1 = $2;
PREPARE
```

Implement parameter type analysis for re-assign (Update) operation SQL of Prepared Statement

---

Cargo.lock

No issue to close.
`cargo-deny` of CI reports issues on dependencies `ordered-float` and `lock_api` (which is only depended by `parking_lot`).
```
error[A001]: ordered_float:NotNan may contain NaN after panic in assignment operators
┌─ /github/workspace/Cargo.lock:89:1
│
89 │ ordered-float 2.0.0 registry+https://github.com/rust-lang/crates.io-index
│ ------------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2020-0082
= Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0082
```
```
warning[A004]: Some lock_api lock guard objects can cause data races
┌─ /github/workspace/Cargo.lock:69:1
│
69 │ lock_api 0.4.1 registry+https://github.com/rust-lang/crates.io-index
│ -------------------------------------------------------------- …
```

Update dependencies for cargo-deny issues

---

.github/workflows/merge.yaml
.github/workflows/pull-requests.yml

Closes #420 
configures Github action to run Java compatibility tests on pull requests (not required for CI success/failure).
References [README](https://github.com/alex-dukhno/database#running-compatibility-tests-locally) for running Java compatibility tests on local.
No.
No special client output.

Configure GH action for Java compatibility tests on pull requests

---

Cargo.lock
data/catalog/src/in_memory.rs
data/catalog/src/lib.rs
data_manipulation/query_result/src/lib.rs
data_manipulation/typed_queries/Cargo.toml
data_manipulation/typed_queries/src/lib.rs
data_manipulation/typed_tree/src/lib.rs
data_manipulation/untyped_queries/Cargo.toml
data_manipulation/untyped_queries/src/lib.rs
query_analyzer/src/lib.rs
query_analyzer/src/tests/updates/expressions.rs
query_processing/type_inference/src/lib.rs
server/node/src/query_engine/mod.rs
server/node/src/query_engine/tests/mod.rs
server/node/src/query_engine/tests/update.rs
write_query/executor/src/lib.rs

Closes #401
use new query engine for update queries
no
no changes

use new query engine for update queries

---

Cargo.lock
node_engine/src/lib.rs
node_engine/src/query_engine/mod.rs
node_engine/src/query_engine/tests/mod.rs
node_engine/src/query_engine/tests/predicate.rs
postgres/query_parser/Cargo.toml
postgres/query_parser/src/lib.rs
postgres/query_parser/src/tests/mod.rs
postgres/query_parser/src/tests/predicate.rs
sql_engine/catalog/src/lib.rs
sql_engine/data_manipulation/operators/Cargo.toml
sql_engine/data_manipulation/operators/src/lib.rs
sql_engine/data_manipulation/query_plan/src/lib.rs
sql_engine/data_manipulation/typed_queries/src/lib.rs
sql_engine/data_manipulation/untyped_queries/src/lib.rs
sql_engine/entities/types/src/lib.rs
sql_engine/query_analyzer/src/lib.rs
sql_engine/query_analyzer/src/tests/delete.rs
sql_engine/query_analyzer/src/tests/selects/expressions.rs
sql_engine/query_analyzer/src/tests/updates/expressions.rs
sql_engine/query_planner/src/lib.rs
sql_engine/query_processing/type_inference/src/lib.rs
sql_engine/scalar/src/lib.rs
storage/in_memory/src/lib.rs
tests/compatibility/src/test/groovy/io/isomorphicdb/simple/BasicQueryOperationsSpec.groovy

add the simplest support for `where` clause in `select`, `update` and `delete` queries for simple PostgreSQL queries
```
postgres=> create schema schema_name;
CREATE SCHEMA
postgres=> create table schema_name.table_name (col1 smallint, col2 smallint, col3 smallint);
CREATE TABLE
postgres=> insert into schema_name.table_name values (1, 2, 3), (4, 5, 6), (7, 8, 9);
INSERT 0 3
postgres=> update schema_name.table_name set col1 = 7 where col1 = 4;
UPDATE 1
postgres=> select * from schema_name.table_name where col1 = 4
postgres-> ;
col1 | col2 | col3
------+------+------
(0 rows)
postgres=> select * from schema_name.table_name where col1 = 7;
col1 | col2 | col3
------+------+------
7 |    5 |    6
7 |    8 |    9
(2 rows)
postgres=> delete from …
```

Add Filter operator to Select, Update, Delete query plans
